Dodao installation guide
DorijanJ/TeachABit pull request #29
Opened 2024-10-29 14:28 UTC by MatejJurisic

2024-10-30 09:51 UTC, DorijanJ requested changes
Umjesto Installation.md stavi u README.md ima (malo se tesko vidi) pod #instalacija (ispod tehnologije), pretpostavljam da tamo treba ici

2024-10-30 10:34 UTC, MatejJurisic commented
Je li ok da README bude toliko dugacak, ako je stavit cu tamo.

2024-10-30 11:19 UTC, DorijanJ commented
Navodno tako treba biti.

2024-11-02 13:22 UTC, DorijanJ approved these changes

2024-11-02 13:22 UTC, merged