Povezano pretraživanje tečajeva s backendom
DorijanJ/TeachABit pull request #75
Opened 2024-11-12 21:54 UTC by ivanmitar35

Povezano pretraživanje tečajeva s backendom pomoću postojećih api poziva. Prikaz tečajeva su samo naslovi odgovarajućih tečajeva u karticama.
Dodan je i gumb "Stvori tečaj" po uzoru na gumb za stvaranje objava, ali bez funkcionalnosti.

2024-11-13 07:02 UTC, MatejJurisic requested changes

2024-11-13 07:02 UTC, MatejJurisic commented on src/TeachABit.Front/src/pages/tecajevi_temp/Tecajevi.tsx
> +                    <SearchBox onSearch={GetTecajList} />
Aj samo ovo stavi izvan ovog conditiona da je user logged in tak da se moze searchat i dok nisi ulogiran.

2024-11-14 12:34 UTC, ivanmitar35 commented
Maknuo sam uvjet za ulogiranost, ali sam zaboravio da treba postojati zbog gumba "Stvori tečaj". Vratit ću ga danas.

2024-12-16 20:04 UTC, MatejJurisic approved these changes

2024-12-16 20:05 UTC, merged